### ISSUE TITLE
Request for Patcher for RaceMenuHH (read NiFloatExtraData from nif file shapes)

### ISSUE THREAD

**Issue by Langmans** [TokcDK/SynHeelsSoundAdd#4] opened 2022-09-13 17:58 UTC
A lot of SE/AE mods use https://www.nexusmods.com/skyrimspecialedition/mods/18045.

How this can be supported? A modder can do the following to offset boot/heels meshes like so:

> Alternatively, you can do the same edit in [NifSkope](https://github.com/niftools/nifskope/releases).
> Right-click a BSTriShape/NiTriShape block in the high heels NIF file and choose Attach Extra Data.
> Attach a **NiFloatExtraData** block and give it the name HH_OFFSET.
> Enter the right height offset value for your high heels.

Any shape in a NIF file can have a property NiFloatExtraData (outfitstudio) or BSTriShape/NiTriShape  with name HH_OFFSET. 
If that is found, then the armor addon might be high heels. I recommend letting the user configure the minimum HH_OFFSET for when boots are heels (for example, more then 3).

Not sure if your NIOHH patcher only reads the binary data as text, if so, then something like nifly (https://github.com/ousnius/nifly) can probably do that right?

**Comment by TokcDK** [comment] 2022-09-17 17:56
> `Right-click a BSTriShape/NiTriShape block in the high heels NIF file and choose Attach Extra Data.
Attach a NiFloatExtraData block and give it the name HH_OFFSET.
Enter the right height offset value for your high heels."` 
It same like NIOHH. Maybe I need to add option to select string to search in nif to be possible enter HH_OFFSET into list.

**Comment by TokcDK** [comment] 2022-09-17 18:23
Added option in settings to select nif marker string manually. In Synthesis selected the patcher and in right panel in Branch group uncheck checkbox Main and enter **dev** or **beta** instead of **main** then patcher will be updated and the option must appear in patcher Settings.

**Comment by TokcDK** [comment] 2022-09-18 18:12
If the change is working please post about it to move changes into main branch and close the issue.

**Comment by Langmans** [comment] 2022-09-21 18:17
Code looks awesome!

Sorry, I don't have a computer with SSE installed at the moment, so I can't test it right now. But in theory it should work.

But having a minimum HH_OFFSET would really be nice tho. And there a lot more heels that use Racemenu High Heels fixes then there are for HDT High Heels.

A good example is Sotteta Huntress outfit.
It would be a good idea to change the footstep sounds for the platform heels, but not the boots.
Platform Heels have a HH_OFFSET of 18. 
![image](https://user-images.githubusercontent.com/756540/191578709-3377449e-efa5-4938-8b9f-3fe0886a41d4.png)
HDT boots have a HH_OFFSET of 4. 
![image](https://user-images.githubusercontent.com/756540/191578797-bdf939b6-7a3a-4bc7-a9b9-e1e1f48d5f0c.png)
As you can see, adding heels sound to the boots does not make sense.

The text to search for in the NIF file is HH_OFFSET as stated by ousnious, but it's not possible without nifly to instead have a minimum for this, is it? The float does not follow the HH_OFFSET string as it is a table in the NIF file.
![image](https://user-images.githubusercontent.com/756540/191579654-e98273ae-f2fb-41f4-ba16-7f97d5e67523.png)

**Comment by Langmans** [comment] 2022-09-21 18:23
None the less, your effort is highly appreciated! I hope you like the challenge to implement nifly :D

**Comment by TokcDK** [comment] 2022-09-23 06:01
As I see from screenshot the search itself is working.
But you mean not only search highheels marker but also check parameter value to not add sound when the value lesser of some number?
In this case I need atleast one nif file where rmhh parameter added.

**Comment by Langmans** [comment] 2022-09-26 17:58
> But you mean not only search highheels marker but also check parameter value to not add sound when the value lesser of some number?

Yes. A threshold for the float value of HH_OFFSET. I hope you can clearly see the problem.

> In this case I need atleast one nif file where rmhh parameter added.

Like I said in previous post, Sotteta Huntress BHUNP is a very good example. You can download this file: https://www.nexusmods.com/skyrimspecialedition/mods/42532?tab=files&file_id=170681
Inside CalienteTools\BodySlide\ShapeData\DX Sotteta Huntress Outfit [BHUNP] are

- DX Sotteta Huntress Boots HH [BHUNP].nif (4)
- DX Sotteta Huntress Boots Platform [BHUNP].nif (18)

**Comment by TokcDK** [comment] 2022-09-27 07:42
added read nif using nifly and added option for min hh offset value
Test if it will work for you. Set branch to **beta** in Synthesis for the patcher. There is patcher settings must appear option to set min hh offset.

**Comment by TokcDK** [comment] 2022-10-01 06:56
If it is work now as intended you can close the issue and I will move changes in main version

**Comment by TokcDK** [comment] 2022-10-04 13:58
Tested it several times and it working. I will close the issue but you can reopen it or open new if it will need.

**Closed as completed by TokcDK** 2022-10-04 13:58 UTC
Labels: enhancement

**Comment by Langmans** [comment] 2022-10-15 13:06
Hey, thanks so much and sorry for not responding, I was on holiday so I couldn't test :) 

EDIT: And it sure does work. Using this with [Dae's Dangerous Domain 2 modlist](https://next.nexusmods.com/skyrimspecialedition/collections/gnfjwh?tab=about) (1400+ mods):

![afbeelding_2022-10-17_193754423](https://user-images.githubusercontent.com/756540/196245285-0467aa7e-1df5-4854-bbc5-d1ed41bd41d2.png)
